### ISSUE TITLE
RD : Phpdoc parser

### ISSUE THREAD

**Issue by jheussler** [objective-php/documentation#1]
Find a free phpdoc parser. Data will need to be exported as raw data (json, xml, whatever), not as html template

**Comment by louis-cuny** [comment]
I tried a lot of little PhpDoc parser from github but neither do the job like we would like.

I found one way to export in an xml file using phpDocumentor. When the tool is installed with composer, you just have to run the following command : ./vendor/bin/phpdoc -d ./src -t output-dir --template=xml
Then you will find an structure.xml file with all data we need.
BUT, I tested this with the primitives repository and many missing or uncomplete phpdoc didn't passed the validator.

**Comment by louis-cuny** [comment]
Among all the documentations on php tools I found, those who did use the phpdoc used an api-doc generator such as phpDocumentor, sami, etc and a user-guide documentation written in markdown or similar. It's not worthy to try to mix the two types of docs.

**Comment by louis-cuny** [comment]
<del>First choice now for me : Use sami and make a custom template to get the rending we wont according to our design</del>

**Comment by louis-cuny** [comment]
Since we wont to generate many of the md files directly from a script using the phpdoc. 
We will need anything to get precise DocBlock content and manipulate the data. 
We will have to use php Reflection.

This little tool can facilitate us the work in getting the content of a DocBlock in an array : https://github.com/kamermans/docblock-reflection
OR sami's docBlock parser : github.com/FriendsOfPHP/Sami/tree/master/Sami/Parser
OR phpDocumentor's docBlock parser : github.com/phpDocumentor/ReflectionDocBlock

This parser : github.com/gossi/docblock uses phpDocumentor's parser but may simplify things and writing.
phpDocumentor/reflectionDocBlock make's possible to make custom tags besides to take a short and long description. Maybe we have here a good solution.

**Comment by louis-cuny** [comment]
Tutorial who seems to be able to help us with our reflection needs :
https://openclassrooms.com/courses/programmez-en-oriente-objet-en-php/l-api-de-reflexivite#/id/r-1667551

They use a lib called Addendum who complete the original PHP reflection classes like ReflectionClass.
They add Classes for annotations with ReflectionAnnotatedClass.

They work only with tags like this : 
/**
\* @tagName(Value content anything)
*/
They are actually annotations, like in JavaEE

**Comment by louis-cuny** [comment]
I finally used phpDocumentor/reflectionDocBlock with symfony's finder to generate the config-directive Markdown file

**Comment by louis-cuny** [comment]
Now we wont a doc-api from the entire components and phpdoc.
We could write a new parser like for the donfig-directoy.md doc but it will be big. I found many tools who generates Md files from phpdoc: 

Using phpDocumentor :
   - cvuorinen/phpdoc-markdown-public	
  🔴 Dont work, caused by the uncomplete phpdoc  
   - evert/lib-phpdoc-md 			
  🔴 Dont work, caused by the uncomplete phpdoc	
   - modgen-net/lib-phpdoc-md      		
  🔴 Dont work, caused by the uncomplete phpdoc

Without phpDocumentor :
   - diversen/php-markdown-docs  	
🔴  works with one class at once and use a old [DISCONTINUED] parser
   - clean/lib-phpdoc-md 		
🔶  This use phtml template. Doesn't support the herited doc
   - alphayax/phpdoc_md	
🔶  write a really shorter doc with regrouping data in arrays. This use mustache templates. Doesn't support the herited doc

Using Sami : 
   - tomasfejfar/sami-github
💚 close to perfection, this is a Markdown template for Sami. It remains a problem with a composer conflict with codeception for many librarie versions. Can be a good choice because our website will also take the hard-writted markdown files. The stylesheets and html architecture would be coherent 


I'm going to try them and found the best one for our needs

PhpDocumentor is to ban, because we dont respect the perfect phpdoc form

**Comment by louis-cuny** [comment]
# One file generated using clean/lib-phpdoc-md, simply

# ObjectivePHP\Primitives\PrimitiveInterface  

Interface PrimitiveInterface

JsonSerializable: each primitive must be serializable by json_encode()  

## Implements:
JsonSerializable



## Methods

| Name | Description |
|------|-------------|
|[cast](#primitiveinterfacecast)|Convert a value to Primitive|
|[copy](#primitiveinterfacecopy)|Return a cloned primitive|
|[getInternalValue](#primitiveinterfacegetinternalvalue)|Return the primitive value in its native representation|
|[jsonSerialize](#primitiveinterfacejsonserialize)||
|[setInternalValue](#primitiveinterfacesetinternalvalue)|Set the primitive object initial value|




### PrimitiveInterface::cast  

**Description**

```php
public static cast (mixed $value)
```

Convert a value to Primitive 

 

**Parameters**

* `(mixed) $value`

**Return Values**

`\PrimitiveInterface`





### PrimitiveInterface::copy  

**Description**

```php
public copy (void)
```

Return a cloned primitive 

 

**Parameters**

`This function has no parameters.`

**Return Values**

`\PrimitiveInterface`





### PrimitiveInterface::getInternalValue  

**Description**

```php
public getInternalValue (void)
```

Return the primitive value in its native representation 

 

**Parameters**

`This function has no parameters.`

**Return Values**

`mixed`





### PrimitiveInterface::jsonSerialize  

**Description**

```php
public jsonSerialize (void)
```

 

 

**Parameters**

`This function has no parameters.`

**Return Values**




### PrimitiveInterface::setInternalValue  

**Description**

```php
public setInternalValue (mixed $value)
```

Set the primitive object initial value 

 

**Parameters**

* `(mixed) $value`

**Return Values**

**Comment by louis-cuny** [comment]
# One file generated using clean/lib-phpdoc-md
# Primitives

**Namespace**  : ObjectivePHP\Primitives

# Overview

- [Collection](./Collection/__NAMESPACE__.md)
    - [AbstractCollection](Collection/__NAMESPACE__.md#AbstractCollection)
    - [Collection](Collection/__NAMESPACE__.md#Collection)
    - [CollectionInterface](Collection/__NAMESPACE__.md#CollectionInterface)
- [Exception](./Exception/__NAMESPACE__.md)
    - [PrimitiveException](Exception/__NAMESPACE__.md#PrimitiveException)
    - [CollectionException](Exception/__NAMESPACE__.md#CollectionException)
    - [BreakException](Exception/__NAMESPACE__.md#BreakException)
    - [UnderflowException](Exception/__NAMESPACE__.md#UnderflowException)
    - [UnsupportedTypeException](Exception/__NAMESPACE__.md#UnsupportedTypeException)
- [String](./String/__NAMESPACE__.md)
    - [Camel](String/__NAMESPACE__.md#Camel)
    - [Snake](String/__NAMESPACE__.md#Snake)
    - [Str](String/__NAMESPACE__.md#Str)
- [AbstractPrimitive](__NAMESPACE__.md#AbstractPrimitive)
- [PrimitiveInterface](__NAMESPACE__.md#PrimitiveInterface)


---
<a name="AbstractPrimitive"></a>
## AbstractPrimitive

**Class**  : ObjectivePHP\Primitives\AbstractPrimitive

### Public methods

| Method | Description |
|---|---|
| `getInternalValue` | {@inheritdoc} |
| `copy` | {@inheritdoc} |

<a name="PrimitiveInterface"></a>
## PrimitiveInterface

**Interface**  : ObjectivePHP\Primitives\PrimitiveInterface

### Public methods

| Method | Description |
|---|---|
| `setInternalValue` | Set the primitive object initial value |
| `getInternalValue` | Return the primitive value in its native representation |
| `copy` | Return a cloned primitive |
| `cast` | Convert a value to Primitive |

**Comment by louis-cuny** [comment]
I used Sami (internally phpDocumentor/reflectiondocblock)
