### ISSUE TITLE
RD : Website template

### ISSUE THREAD

**Issue by jheussler** [objective-php/documentation#2]
Find a doc style template to use

**Comment by louis-cuny** [comment]
We will work with the best : Objective-php
For the style, we could start with something like docusaurus or docsify but these templates generate a full website with markdown files for content.

 run Docusaurus with user-doc -> add the generated phpdoc      
OR use a little markdown parser to freely separate the content from the form

Docusaurus and docsify work in nodejs, maybe unnecessary big to work with objective-php. This tools are made to work alone

**Comment by louis-cuny** [comment]
We can start with the basic Bootstrap css framework. 
We can catch the stylesheets from a sami, phpDocumentor, docsify or docusaurus template
We can start with bootstrap with a free template (no great found yet)

**Comment by louis-cuny** [comment]
First choice now for me : Start with a simple bootstrap starter:
https://getbootstrap.com/docs/4.0/examples/dashboard/
OR simply https://getbootstrap.com/docs/4.0/examples/starter-template/

**Comment by louis-cuny** [comment]
Css proposal for markdown = github.com/sindresorhus/github-markdown-css

**Comment by louis-cuny** [comment]
List of website using a sami api doc AND a developer doc : 
 - http://api.silverstripe.org/4/index.html
 - https://api.roadiz.io/
 
Others just make a fully separated api-doc exactly like this : 
 - https://twig.symfony.com/api/2.x/index.html

**Comment by louis-cuny** [comment]
I tried many sami themes from github, some didn't worked, the others: 

- kunalvarma05/flat-theme
- SilentByte/sami-silentbyte
 🔻 Both very similar form from the original, just beautifuller 
- roadiz/roadiz-sami-theme
 🔹 Fully customized and integrated into a website, nice work
 - Gendoria/sami-one-page-theme
 🔸 Interessant use, because we will have to integrate many api-doc from different components. Could be a good way to simplify the complex hierarchy-ergonomy 
 - devedge/sami-github
 🔺 Output in markdown, perfectly made for github. Can be translated in html with a simple md to html parser (commonmark.thephpleague.com, github.com/objective-php/documentation/issues/7).

These are just to get ideas how we can compose our custom sami template and render.

**Comment by louis-cuny** [comment]
I start with the roadiz/roadiz-sami-theme and custom it.

Now we have a choice to make:

Generating finished html files from sami with the websites layout ? If we modify the layout we must be able to regenerate the full doc. Links have to be adapted
OR make html/phtml files that we include in the layout for rendering ?

**Comment by louis-cuny** [comment]
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/13121784/40177251-515aa6fe-59de-11e8-9312-baaaab94ba98.png">
